version: "3"
services:
  # Postgres
  db:
    image: 'postgres:latest'
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB=sysloan_db
      - POSTGRES_USER=proposal_admin
      - POSTGRES_PASSWORD=admin
    networks:
      - some-net

  # Redis
  redis:
    image: redis:3.2.8
    hostname: redis
    networks:
      - some-net

  # RabbitMQ
  rabbit:
    hostname: rabbitmq
    image: rabbitmq:3.6.9
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - some-net

  # Server
  server:
    container_name: server
    restart: unless-stopped
    build: .
    entrypoint: /app/server-entrypoint.sh
    ports: 
      - "8000:8000"
    volumes:
      - static_volume:/app/digitalsys_loan/django_static
    command: python manage.py runserver 0.0.0.0:8000
    links:
      - db
      - rabbit
      - redis
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DJANGO_DB=postgresql
      - POSTGRES_USER=proposal_admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_NAME=sysloan_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=amqp://admin:mypass@rabbitmq:5672
    networks:
      - some-net

  # Celery Worker
  worker:
    restart: unless-stopped
    build: .
    entrypoint: /app/worker-entrypoint.sh
    volumes:
      - static_volume:/app/digitalsys_loan/django_static
    environment:
      - DEBUG=True
      - DJANGO_DB=postgresql
      - POSTGRES_USER=proposal_admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_NAME=sysloan_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=amqp://admin:mypass@rabbitmq:5672
    links:
      - db
      - rabbit
      - redis
      - server
    depends_on:
      - rabbit
      - server
    networks:
      - some-net

networks:
  some-net:
    name: custom_network
    driver: bridge
volumes:
    static_volume: {}
    postgres_data: {}