# Generated by Django 4.2.2 on 2023-06-24 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_info', models.JSONField(null=True)),
                ('proposal_cpf', models.CharField(max_length=12, verbose_name='CPF')),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 6, 24, 4, 38, 16, 494435, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação')),
                ('answer', models.CharField(choices=[('1', 'Pendente'), ('2', 'Aprovada'), ('3', 'Negada')], default='1', max_length=20, verbose_name='Resposta')),
            ],
        ),
        migrations.DeleteModel(
            name='SentProposal',
        ),
    ]
