# Generated by Django 4.2.2 on 2023-06-24 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_rename_proposal_cpf_proposal_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='answer',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Negada', 'Negada')], default='Pendente', max_length=20, verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 6, 17, 19, 734559, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
        ),
    ]
